name: Electron Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-electron:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install Required Build Tools
        shell: powershell
        run: |
          npm config set msvs_version 2019
          npm config set python python3
          npm install -g node-gyp

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: |
          npm run transpile:electron
          npm run build
          npm run dist:win

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: release/*.exe

      - name: Upload Complete Release
        uses: actions/upload-artifact@v4
        with:
          name: complete-release
          path: release/
