name: Electron Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-electron:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Removed cache option

      - name: Install global dependencies
        run: npm install -g node-gyp windows-build-tools@4.0.0 --vs2015 --production

      - name: Install project dependencies
        run: npm install --no-package-lock

      - name: Build TypeScript and Vite App
        run: |
          npm run transpile:electron
          npm run build

      - name: Build Electron App for Windows
        run: npm run dist:win

      - name: List release directory
        shell: powershell
        run: |
          if (Test-Path "release") {
            Get-ChildItem -Path "release" -Recurse | ForEach-Object { $_.FullName }
          } else {
            Write-Error "Release directory not found"
          }

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            release/*.exe
            release/**/*.exe

      - name: Upload Full Release Folder
        uses: actions/upload-artifact@v4
        with:
          name: full-release
          path: release/
