
name: Electron Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-electron:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --verbose
          npm install --global windows-build-tools

      - name: Build TypeScript and Vite App
        run: |
          npm run transpile:electron
          npm run build

      - name: Build Electron App for Windows
        run: npm run dist:win

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: release/*.exe

      - name: Upload Full Release Folder
        uses: actions/upload-artifact@v4
        with:
          name: full-release
          path: release/
